# Generated by Django 4.0.1 on 2022-01-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('Position', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
