# Generated by Django 4.0.1 on 2022-01-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_emp_det_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_det',
            name='DOB',
        ),
    ]
